[package]
name = "hb-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
glam = {version = "0.30.8", features = ["bytemuck"]}
image = "0.25.8"
wgpu = "26.0.1"
winit = "0.30.12"
